spec:
  destination:
    server: https://kubernetes.default.svc

argocd:
  enabled: true
  chartVersion: "7.7.3"

cilium:
  enabled: true
  chartVersion: "1.18.5"

traefik:
  enabled: true
  chartVersion: "38.0.0"

certManager:
  enabled: true
  chartVersion: "v1.19.2"

sealedSecrets:
  enabled: true
  chartVersion: "2.17.2"

externalDns:
  enabled: true
  chartVersion: "1.15.0"

authentik:
  enabled: true
  chartVersion: "2025.10.3"

whoami:
  enabled: true
